Feat/fee 749 not existing query
keen/dashboard-creator pull request #295
Opened 2021-09-16 13:43 UTC by apryka

* https://metakeen.atlassian.net/browse/FEE-749
* https://staging-static.keen.io/build/feat/FEE-749-not-existing-query/index.html

2021-09-20 05:21 UTC, maciejrybaniec requested changes

2021-09-20 05:21 UTC, maciejrybaniec commented on src/modules/widgets/widgetsSaga.ts
> +  if (action.type === appActions.hideQueryPicker.type) {
Is there any possibility to extract common logic for two flows:
- Select Saved Query for widget
- Create new Query for widget

Then re-use it for two cases:
1. User drops chart widget on Grid
2. User decides to re-connect query after it was removed 

Currently I think that the `createNewChart` saga flow - creates a lot of code duplication.

2021-09-23 14:02 UTC, mczapkowicz approved these changes

2021-09-24 08:25 UTC, maciejrybaniec approved these changes

2021-09-24 08:25 UTC, maciejrybaniec commented
@apryka please fix conflicts

2021-09-24 08:38 UTC, merged